#!/usr/bin/env python3
"""
generate_repo_map.py — Score_Leads Repo Map Generator

Scans the repo and outputs a concise map of:
- Directory tree (filtered, excluding .git, node_modules, etc.)
- Key files with sizes
- Basic structure overview

Output: .agent/repo-map.md
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Directories to exclude from the tree
EXCLUDE_DIRS = {
    '.git', 'node_modules', '__pycache__', '.next', 'dist', 'build',
    '.cache', '.turbo', 'coverage', '.nyc_output'
}

# Files to exclude
EXCLUDE_FILES = {
    '.DS_Store', 'Thumbs.db', 'desktop.ini'
}

# Key file patterns to highlight
KEY_PATTERNS = {
    'package.json', 'tsconfig.json', 'vite.config.ts', 'vite.config.js',
    '.gitignore', 'README.md', 'Project_Context.md',
    'devcontainer.json', 'ci.yml'
}


def get_repo_root():
    """Get the repo root (directory containing this script's parent)."""
    script_dir = Path(__file__).resolve().parent
    return script_dir.parent


def build_tree(root_path, prefix="", max_depth=5, current_depth=0):
    """Build a directory tree string."""
    if current_depth > max_depth:
        return ["    " * current_depth + "... (max depth reached)"]

    lines = []
    try:
        entries = sorted(root_path.iterdir(), key=lambda e: (not e.is_dir(), e.name.lower()))
    except PermissionError:
        return [prefix + "⚠️ Permission denied"]

    # Filter entries
    filtered = []
    for entry in entries:
        if entry.name in EXCLUDE_DIRS and entry.is_dir():
            continue
        if entry.name in EXCLUDE_FILES:
            continue
        filtered.append(entry)

    for i, entry in enumerate(filtered):
        is_last = (i == len(filtered) - 1)
        connector = "└── " if is_last else "├── "
        extension = "    " if is_last else "│   "

        if entry.is_dir():
            child_count = sum(1 for _ in entry.iterdir()) if entry.exists() else 0
            lines.append(f"{prefix}{connector}📁 {entry.name}/ ({child_count} items)")
            lines.extend(build_tree(entry, prefix + extension, max_depth, current_depth + 1))
        else:
            size = entry.stat().st_size
            size_str = format_size(size)
            marker = " ⭐" if entry.name in KEY_PATTERNS else ""
            lines.append(f"{prefix}{connector}📄 {entry.name} ({size_str}){marker}")

    return lines


def format_size(size_bytes):
    """Format file size in human-readable format."""
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.1f} MB"


def find_key_files(root_path):
    """Find key files in the repo."""
    key_files = []
    for root, dirs, files in os.walk(root_path):
        # Skip excluded dirs
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for f in files:
            if f in KEY_PATTERNS:
                full_path = Path(root) / f
                rel_path = full_path.relative_to(root_path)
                size = full_path.stat().st_size
                key_files.append((str(rel_path), format_size(size)))
    return sorted(key_files)


def generate_map():
    """Generate the repo map."""
    root = get_repo_root()
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# Repo Map — Score_Leads",
        "",
        f"> Auto-generated by `scripts/generate_repo_map.py` on {timestamp}",
        "> Do NOT edit manually — regenerate with: `python scripts/generate_repo_map.py`",
        "",
        "---",
        "",
        "## Directory Tree",
        "",
        f"📁 {root.name}/",
    ]

    tree = build_tree(root)
    lines.extend(tree)

    lines.extend([
        "",
        "---",
        "",
        "## Key Files",
        "",
        "| File | Size |",
        "|------|------|",
    ])

    for path, size in find_key_files(root):
        lines.append(f"| `{path}` | {size} |")

    lines.extend([
        "",
        "---",
        "",
        f"*Generated: {timestamp}*",
        "",
    ])

    # Write output
    output_path = root / ".agent" / "repo-map.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"✅ Repo map generated: {output_path}")
    print(f"   Files scanned from: {root}")
    print(f"   Timestamp: {timestamp}")


if __name__ == "__main__":
    generate_map()
