#!/usr/bin/env node
/**
 * generate_repo_map.js — Score_Leads Repo Map Generator
 *
 * Scans the repo and outputs a concise map of:
 * - Directory tree (filtered, excluding .git, node_modules, etc.)
 * - Key files with sizes
 * - Basic structure overview
 *
 * Output: .agent/repo-map.md
 *
 * Usage: node scripts/generate_repo_map.js
 */

const fs = require("fs");
const path = require("path");

// Directories to exclude from the tree
const EXCLUDE_DIRS = new Set([
  ".git",
  "node_modules",
  "__pycache__",
  ".next",
  "dist",
  "build",
  ".cache",
  ".turbo",
  "coverage",
  ".nyc_output",
]);

// Files to exclude
const EXCLUDE_FILES = new Set([".DS_Store", "Thumbs.db", "desktop.ini"]);

// Key file patterns to highlight
const KEY_PATTERNS = new Set([
  "package.json",
  "tsconfig.json",
  "vite.config.ts",
  "vite.config.js",
  ".gitignore",
  "README.md",
  "Project_Context.md",
  "devcontainer.json",
  "ci.yml",
]);

function getRepoRoot() {
  return path.resolve(__dirname, "..");
}

function formatSize(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function buildTree(dirPath, prefix = "", maxDepth = 5, currentDepth = 0) {
  const lines = [];
  if (currentDepth > maxDepth) {
    lines.push(`${prefix}... (max depth reached)`);
    return lines;
  }

  let entries;
  try {
    entries = fs.readdirSync(dirPath, { withFileTypes: true });
  } catch (err) {
    lines.push(`${prefix}⚠️ Permission denied`);
    return lines;
  }

  // Sort: directories first, then alphabetically
  entries.sort((a, b) => {
    if (a.isDirectory() && !b.isDirectory()) return -1;
    if (!a.isDirectory() && b.isDirectory()) return 1;
    return a.name.toLowerCase().localeCompare(b.name.toLowerCase());
  });

  // Filter
  const filtered = entries.filter((e) => {
    if (e.isDirectory() && EXCLUDE_DIRS.has(e.name)) return false;
    if (EXCLUDE_FILES.has(e.name)) return false;
    return true;
  });

  filtered.forEach((entry, i) => {
    const isLast = i === filtered.length - 1;
    const connector = isLast ? "└── " : "├── ";
    const extension = isLast ? "    " : "│   ";
    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      let childCount = 0;
      try {
        childCount = fs.readdirSync(fullPath).length;
      } catch {}
      lines.push(
        `${prefix}${connector}📁 ${entry.name}/ (${childCount} items)`,
      );
      lines.push(
        ...buildTree(fullPath, prefix + extension, maxDepth, currentDepth + 1),
      );
    } else {
      let size = 0;
      try {
        size = fs.statSync(fullPath).size;
      } catch {}
      const marker = KEY_PATTERNS.has(entry.name) ? " ⭐" : "";
      lines.push(
        `${prefix}${connector}📄 ${entry.name} (${formatSize(size)})${marker}`,
      );
    }
  });

  return lines;
}

function findKeyFiles(rootPath) {
  const keyFiles = [];

  function walk(dir) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!EXCLUDE_DIRS.has(entry.name)) walk(fullPath);
      } else if (KEY_PATTERNS.has(entry.name)) {
        const relPath = path.relative(rootPath, fullPath).replace(/\\/g, "/");
        let size = 0;
        try {
          size = fs.statSync(fullPath).size;
        } catch {}
        keyFiles.push({ path: relPath, size: formatSize(size) });
      }
    }
  }

  walk(rootPath);
  return keyFiles.sort((a, b) => a.path.localeCompare(b.path));
}

function generateMap() {
  const root = getRepoRoot();
  const rootName = path.basename(root);
  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19);

  const lines = [
    "# Repo Map — Score_Leads",
    "",
    `> Auto-generated by \`scripts/generate_repo_map.js\` on ${timestamp}`,
    "> Do NOT edit manually — regenerate with: `node scripts/generate_repo_map.js`",
    "",
    "---",
    "",
    "## Directory Tree",
    "",
    `📁 ${rootName}/`,
    ...buildTree(root),
    "",
    "---",
    "",
    "## Key Files",
    "",
    "| File | Size |",
    "|------|------|",
    ...findKeyFiles(root).map((f) => `| \`${f.path}\` | ${f.size} |`),
    "",
    "---",
    "",
    `*Generated: ${timestamp}*`,
    "",
  ];

  const outputPath = path.join(root, ".agent", "repo-map.md");
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");

  console.log(`✅ Repo map generated: ${outputPath}`);
  console.log(`   Files scanned from: ${root}`);
  console.log(`   Timestamp: ${timestamp}`);
}

generateMap();
